const terraGalleryData = [
  {
    id: 1,
    slug: "burnt-leek-bone-marrow-sea-salt",
    title: "Burnt Leek, Bone Marrow & Sea Salt",
    category: "Signature Dishes",
    subcategory: "Vegetables",
    chef: "Marco Bellini",
    season: "Winter",
    year: 2024,
    badge: "Photo of the Month",
    badgeStyle: "terra",
    description:
      "A winter signature. The leek spends 40 minutes directly on the coals — until the outer layers are completely carbonised. What remains inside is silk.",
    technique: ["Live Fire", "Reduction"],
    ingredients: ["Leek", "Bone Marrow", "Sea Salt", "Brown Butter"],
    tags: ["fire", "winter", "signature", "vegetable"],
    isFeatured: true,
    isRecentlyAdded: false,
    gridSize: "wide",
    placeholder: "🌿",
    imageUrl:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    imageAlt: "Burnt Leek, Bone Marrow & Sea Salt",
  },
  {
    id: 2,
    slug: "dry-aged-cote-de-boeuf-chimichurri",
    title: "Dry-Aged Côte de Boeuf, Chimichurri Verde",
    category: "Grill & Fire",
    subcategory: "Beef",
    chef: "Tarık Yıldız",
    season: "All Year",
    year: 2024,
    badge: "Signature",
    badgeStyle: "terra",
    description:
      "45 days. Open flame. Four minutes per side. The rest is Tarık.",
    technique: ["Dry Aging", "Live Fire", "Open Flame"],
    ingredients: [
      "Côte de Boeuf",
      "Chimichurri Verde",
      "Sea Salt",
      "Smoked Butter",
    ],
    tags: ["beef", "fire", "signature", "aged"],
    isFeatured: false,
    isRecentlyAdded: true,
    gridSize: "wide",
    placeholder: "🥩",
    imageUrl:
      "https://images.unsplash.com/photo-1556269923-e4ef51d69638?w=800&q=80",
    imageAlt: "Dry-Aged Côte de Boeuf, Chimichurri Verde",
  },
  {
    id: 3,
    slug: "langoustine-saffron-broth-sea-urchin",
    title: "Langoustine, Saffron Broth & Sea Urchin Butter",
    category: "Seafood",
    subcategory: "Shellfish",
    chef: "Sofia Andreou",
    season: "Spring",
    year: 2024,
    badge: "Mediterranean",
    badgeStyle: "dark",
    description:
      "Sofia's most Mediterranean plate — everything from the Aegean, nothing from a tin.",
    technique: ["Poaching", "Emulsification", "Reduction"],
    ingredients: [
      "Langoustine",
      "Saffron",
      "Sea Urchin",
      "White Wine",
      "Shallots",
    ],
    tags: ["seafood", "mediterranean", "shellfish", "spring"],
    isFeatured: false,
    isRecentlyAdded: true,
    gridSize: "half",
    placeholder: "🦐",
    imageUrl:
      "https://images.unsplash.com/photo-1579783411194-f697db862dcd?w=800&q=80",
    imageAlt: "Langoustine, Saffron Broth & Sea Urchin Butter",
  },
  {
    id: 4,
    slug: "caramelised-fig-tart",
    title: "Caramelised Fig Tart",
    category: "Pastry",
    subcategory: "Tarts",
    chef: "Kenji Tanaka",
    season: "Autumn",
    year: 2024,
    badge: "Pastry",
    badgeStyle: "dark",
    description: "Kenji's most requested dessert since the day it debuted.",
    technique: ["Caramelisation", "Blind Baking", "Pastry Cream"],
    ingredients: [
      "Fresh Figs",
      "Almond Cream",
      "Butter Pastry",
      "Caramel",
      "Thyme",
    ],
    tags: ["dessert", "pastry", "fig", "autumn"],
    isFeatured: false,
    isRecentlyAdded: true,
    gridSize: "narrow",
    placeholder: "🍮",
    imageUrl:
      "https://images.unsplash.com/photo-1663530761401-15eefb544889?w=800&q=80",
    imageAlt: "Caramelised Fig Tart",
  },
  {
    id: 5,
    slug: "cured-salmon-dill-oil",
    title: "Cured Salmon, Dill Oil",
    category: "Seafood",
    subcategory: "Cured Fish",
    chef: "Nora Hartmann",
    season: "All Year",
    year: 2024,
    badge: "Awarded",
    badgeStyle: "gold",
    description: "Nora's recipe. On the menu, unchanged, since 2015.",
    technique: ["Curing", "Cold Smoking", "Oil Infusion"],
    ingredients: ["Atlantic Salmon", "Dill", "Sea Salt", "Sugar", "Lemon Zest"],
    tags: ["seafood", "cured", "classic", "awarded"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "narrow",
    placeholder: "🐟",
    imageUrl:
      "https://images.unsplash.com/photo-1560717845-968823efbee1?w=800&q=80",
    imageAlt: "Cured Salmon, Dill Oil",
  },
  {
    id: 6,
    slug: "spring-herb-selection",
    title: "Spring Herb Selection",
    category: "Ingredients",
    subcategory: "Herbs",
    chef: "Marco Bellini",
    season: "Spring",
    year: 2024,
    badge: "Seasonal",
    badgeStyle: "sage",
    description: "Delivered every morning from our supplier in Bursa.",
    technique: ["Foraging", "Selection"],
    ingredients: ["Tarragon", "Chervil", "Lovage", "Wild Garlic", "Sorrel"],
    tags: ["ingredients", "herbs", "spring", "local"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "narrow",
    placeholder: "🌿",
    imageUrl:
      "https://images.unsplash.com/photo-1628919350249-eb45d8829629?w=800&q=80",
    imageAlt: "Spring Herb Selection",
  },
  {
    id: 7,
    slug: "confit-onion-6-hours",
    title: "Confit Onion, 6 Hours",
    category: "Technique",
    subcategory: "Confit",
    chef: "Leila Şahin",
    season: "All Year",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description: "Low and slow until the sugars concentrate completely.",
    technique: ["Confit", "Low Temperature"],
    ingredients: ["White Onion", "Thyme", "Bay Leaf", "Duck Fat", "Vinegar"],
    tags: ["technique", "vegetable", "slow-cook"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🧅",
    imageUrl:
      "https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=800&q=80",
    imageAlt: "Confit Onion, 6 Hours",
  },
  {
    id: 8,
    slug: "morning-delivery-iskilip-greens",
    title: "Morning Delivery — Iskilip Greens",
    category: "Ingredients",
    subcategory: "Greens",
    chef: "Marco Bellini",
    season: "Spring",
    year: 2024,
    badge: "Farm to Table",
    badgeStyle: "sage",
    description: "400 km overnight. On the plate by lunch.",
    technique: ["Selection", "Cold Storage"],
    ingredients: ["Rocket", "Baby Spinach", "Watercress", "Purslane"],
    tags: ["ingredients", "greens", "local", "spring"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🥬",
    imageUrl:
      "https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=800&q=80",
    imageAlt: "Morning Delivery — Iskilip Greens",
  },
  {
    id: 9,
    slug: "house-cured-charcuterie-board",
    title: "House-Cured Charcuterie Board",
    category: "Garde Manger",
    subcategory: "Charcuterie",
    chef: "Nora Hartmann",
    season: "All Year",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "Everything cured, smoked, or preserved in-house. No exceptions.",
    technique: ["Curing", "Smoking", "Fermentation"],
    ingredients: [
      "Pork Loin",
      "Duck Breast",
      "Lardo",
      "Cornichons",
      "Sourdough",
    ],
    tags: ["charcuterie", "cured", "smoked", "board"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🫙",
    imageUrl:
      "https://images.unsplash.com/photo-1514326640560-7d063ef2aed5?w=800&q=80",
    imageAlt: "House-Cured Charcuterie Board",
  },
  {
    id: 10,
    slug: "ten-course-evening-table-setup",
    title: "Ten-Course Evening — Table Setup",
    category: "Private Dining",
    subcategory: "Events",
    chef: "Marco Bellini",
    season: "All Year",
    year: 2024,
    badge: "Tasting Menu",
    badgeStyle: "terra",
    description:
      "The light changes at 8 PM. That's when the tasting menu begins.",
    technique: ["Table Setting", "Service"],
    ingredients: [],
    tags: ["events", "private dining", "tasting menu", "atmosphere"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "half",
    placeholder: "🍷",
    imageUrl:
      "https://images.unsplash.com/photo-1642339147375-c3e037498ab5?w=800&q=80",
    imageAlt: "Ten-Course Evening — Table Setup",
  },
  {
    id: 11,
    slug: "5am-prep-charcoal-run",
    title: "5 AM Prep — The Charcoal Run",
    category: "Behind the Scenes",
    subcategory: "Kitchen Life",
    chef: "Tarık Yıldız",
    season: "All Year",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description: "Before guests arrive, the kitchen is already on fire.",
    technique: ["Live Fire", "Prep"],
    ingredients: [],
    tags: ["behind the scenes", "kitchen", "fire", "morning"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "narrow",
    placeholder: "🔥",
    imageUrl:
      "https://images.unsplash.com/photo-1566063114423-c438c40dcded?w=800&q=80",
    imageAlt: "5 AM Prep — The Charcoal Run",
  },
  {
    id: 12,
    slug: "the-negative-space",
    title: "The Negative Space",
    category: "Plating Series",
    subcategory: "Composition",
    chef: "Marco Bellini",
    season: "All Year",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "Plate as canvas. What's left empty is as deliberate as what's placed.",
    technique: ["Plating", "Composition"],
    ingredients: [],
    tags: ["plating", "composition", "series", "art"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🍃",
    seriesNumber: "001",
    seriesName: "Plating Series",
    imageUrl:
      "https://images.unsplash.com/photo-1623073284788-0d846f75e329?w=800&q=80",
    imageAlt: "The Negative Space",
  },
  {
    id: 13,
    slug: "the-sauce-work",
    title: "The Sauce Work",
    category: "Plating Series",
    subcategory: "Technique",
    chef: "Leila Şahin",
    season: "All Year",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description: "Every smear, drop, and pool is placed by hand. Never poured.",
    technique: ["Sauce", "Plating"],
    ingredients: [],
    tags: ["plating", "sauce", "series", "technique"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "💧",
    seriesNumber: "002",
    seriesName: "Plating Series",
    imageUrl:
      "https://images.unsplash.com/photo-1643757343278-5d50309dfa44?w=800&q=80",
    imageAlt: "The Sauce Work",
  },
  {
    id: 14,
    slug: "the-garnish-edit",
    title: "The Garnish Edit",
    category: "Plating Series",
    subcategory: "Garnish",
    chef: "Kenji Tanaka",
    season: "All Year",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "If it doesn't taste like something, it doesn't belong on the plate.",
    technique: ["Garnish", "Plating"],
    ingredients: [],
    tags: ["plating", "garnish", "series"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🌺",
    seriesNumber: "003",
    seriesName: "Plating Series",
    imageUrl:
      "https://images.unsplash.com/photo-1657566648148-061dc760eca6?w=800&q=80",
    imageAlt: "The Garnish Edit",
  },
  {
    id: 15,
    slug: "the-lighting-moment",
    title: "The Lighting Moment",
    category: "Plating Series",
    subcategory: "Photography",
    chef: "Marco Bellini",
    season: "All Year",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "Every dish is photographed under the same light it's served in. No studio tricks.",
    technique: ["Photography", "Plating"],
    ingredients: [],
    tags: ["plating", "photography", "series", "light"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🕯️",
    seriesNumber: "004",
    seriesName: "Plating Series",
    imageUrl:
      "https://images.unsplash.com/photo-1599206614622-d7dae04bb031?w=800&q=80",
    imageAlt: "The Lighting Moment",
  },
  {
    id: 16,
    slug: "black-truffle-risotto-aged-parmesan",
    title: "Black Truffle Risotto, 36-Month Parmesan",
    category: "Signature Dishes",
    subcategory: "Rice & Grains",
    chef: "Marco Bellini",
    season: "Winter",
    year: 2024,
    badge: "Signature",
    badgeStyle: "terra",
    description:
      "The risotto is finished tableside. The truffle is shaved to order, never before.",
    technique: ["Risotto", "Mantecatura", "Shaving"],
    ingredients: [
      "Carnaroli Rice",
      "Black Truffle",
      "Aged Parmesan",
      "White Wine",
      "Shallots",
    ],
    tags: ["truffle", "risotto", "winter", "signature"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "half",
    placeholder: "🍄",
    imageUrl:
      "https://images.unsplash.com/photo-1611520175743-30ff00129621?w=800&q=80",
    imageAlt: "Black Truffle Risotto, 36-Month Parmesan",
  },
  {
    id: 17,
    slug: "charred-octopus-potato-espuma",
    title: "Charred Octopus, Potato Espuma",
    category: "Seafood",
    subcategory: "Octopus",
    chef: "Sofia Andreou",
    season: "Summer",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "Cooked for three hours in a court-bouillon, then finished hard on the grill. The char is everything.",
    technique: ["Braising", "Grilling", "Espuma"],
    ingredients: ["Octopus", "Potato", "Smoked Paprika", "Olive Oil", "Lemon"],
    tags: ["seafood", "octopus", "grill", "summer"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🐙",
    imageUrl:
      "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=800&q=80",
    imageAlt: "Charred Octopus, Potato Espuma",
  },
  {
    id: 18,
    slug: "venison-tartare-pine-oil",
    title: "Venison Tartare, Pine Oil & Preserved Egg",
    category: "Signature Dishes",
    subcategory: "Tartare",
    chef: "Marco Bellini",
    season: "Autumn",
    year: 2023,
    badge: "Awarded",
    badgeStyle: "gold",
    description:
      "Hand-cut, never minced. The pine oil is distilled in-house from needles collected in Bolu.",
    technique: ["Hand Cutting", "Oil Distillation", "Preservation"],
    ingredients: [
      "Venison Loin",
      "Pine Oil",
      "Preserved Egg Yolk",
      "Capers",
      "Mustard",
    ],
    tags: ["tartare", "venison", "autumn", "awarded"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🦌",
    imageUrl:
      "https://images.unsplash.com/photo-1611464357429-a34ac648a5e9?w=800&q=80",
    imageAlt: "Venison Tartare, Pine Oil & Preserved Egg",
  },
  {
    id: 19,
    slug: "sourdough-cultured-butter",
    title: "TERRA Sourdough & Cultured Butter",
    category: "Behind the Scenes",
    subcategory: "Bread",
    chef: "Kenji Tanaka",
    season: "All Year",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "The starter is seven years old. It has travelled with us through three kitchens.",
    technique: ["Sourdough", "Fermentation", "Churning"],
    ingredients: ["Sourdough Starter", "Bread Flour", "Cream", "Sea Salt"],
    tags: ["bread", "fermentation", "behind the scenes"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🍞",
    imageUrl:
      "https://images.unsplash.com/photo-1663530761401-15eefb544889?w=800&q=80&fit=crop&crop=bottom",
    imageAlt: "TERRA Sourdough & Cultured Butter",
  },
  {
    id: 20,
    slug: "white-asparagus-hollandaise-bottarga",
    title: "White Asparagus, Hollandaise & Bottarga",
    category: "Seasonal",
    subcategory: "Vegetables",
    chef: "Leila Şahin",
    season: "Spring",
    year: 2024,
    badge: "Seasonal",
    badgeStyle: "sage",
    description:
      "Available for eight weeks every year. No exceptions, no extensions.",
    technique: ["Steaming", "Hollandaise", "Curing"],
    ingredients: ["White Asparagus", "Egg Yolk", "Butter", "Lemon", "Bottarga"],
    tags: ["seasonal", "spring", "vegetables", "asparagus"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "half",
    placeholder: "🌾",
    imageUrl:
      "https://images.unsplash.com/photo-1566063114423-c438c40dcded?w=800&q=80&fit=crop&crop=top",
    imageAlt: "White Asparagus, Hollandaise & Bottarga",
  },
  {
    id: 21,
    slug: "chocolate-fondant-miso-caramel",
    title: "Warm Chocolate Fondant, Miso Caramel",
    category: "Pastry",
    subcategory: "Chocolate",
    chef: "Kenji Tanaka",
    season: "Winter",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "The miso adds depth the chocolate alone cannot achieve. Kenji's most personal dish.",
    technique: ["Baking", "Caramelisation", "Miso Fermentation"],
    ingredients: [
      "Dark Chocolate 72%",
      "White Miso",
      "Caramel",
      "Butter",
      "Eggs",
    ],
    tags: ["dessert", "chocolate", "winter", "miso"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🍫",
    imageUrl:
      "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800&q=80",
    imageAlt: "Warm Chocolate Fondant, Miso Caramel",
  },
  {
    id: 22,
    slug: "lamb-saddle-wild-garlic-jus",
    title: "Lamb Saddle, Wild Garlic Jus",
    category: "Grill & Fire",
    subcategory: "Lamb",
    chef: "Tarık Yıldız",
    season: "Spring",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "The saddle is tied and roasted whole. Rested for as long as it cooked.",
    technique: ["Roasting", "Jus", "Resting"],
    ingredients: [
      "Lamb Saddle",
      "Wild Garlic",
      "Rosemary",
      "Butter",
      "Red Wine",
    ],
    tags: ["lamb", "grill", "spring", "fire"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🍖",
    imageUrl:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    imageAlt: "Lamb Saddle, Wild Garlic Jus",
  },
  {
    id: 23,
    slug: "smoked-eel-apple-horseradish",
    title: "Smoked Eel, Apple & Horseradish Cream",
    category: "Garde Manger",
    subcategory: "Smoked Fish",
    chef: "Nora Hartmann",
    season: "Autumn",
    year: 2023,
    badge: null,
    badgeStyle: null,
    description:
      "The eel is smoked over applewood for six hours. The apple is from the same tree.",
    technique: ["Cold Smoking", "Cream Whipping", "Pickling"],
    ingredients: [
      "Smoked Eel",
      "Granny Smith Apple",
      "Horseradish",
      "Crème Fraîche",
    ],
    tags: ["smoked", "eel", "autumn", "garde manger"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🐍",
    imageUrl:
      "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80",
    imageAlt: "Smoked Eel, Apple & Horseradish Cream",
  },
  {
    id: 24,
    slug: "wine-cellar-300-labels",
    title: "The Cellar — 300 Labels",
    category: "Behind the Scenes",
    subcategory: "Wine",
    chef: "Emre Kaya",
    season: "All Year",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "Emre built this from scratch. Every bottle chosen to finish a sentence the food started.",
    technique: ["Wine Selection", "Cellaring"],
    ingredients: [],
    tags: ["wine", "cellar", "behind the scenes"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "half",
    placeholder: "🍾",
    imageUrl:
      "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80",
    imageAlt: "The Cellar — 300 Labels",
  },
  {
    id: 25,
    slug: "burrata-heirloom-tomato-basil",
    title: "Burrata, Heirloom Tomato & Basil Oil",
    category: "Seasonal",
    subcategory: "Cheese",
    chef: "Leila Şahin",
    season: "Summer",
    year: 2024,
    badge: "Summer",
    badgeStyle: "sage",
    description:
      "Only on the menu when the tomatoes are worth it. Usually July and August.",
    technique: ["Cold Setting", "Oil Infusion"],
    ingredients: [
      "Burrata",
      "Heirloom Tomatoes",
      "Basil",
      "Extra Virgin Olive Oil",
      "Fleur de Sel",
    ],
    tags: ["summer", "tomato", "cheese", "seasonal"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🫙",
    imageUrl:
      "https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=800&q=80",
    imageAlt: "Burrata, Heirloom Tomato & Basil Oil",
  },
  {
    id: 26,
    slug: "sea-bass-fennel-saffron-nage",
    title: "Sea Bass, Fennel & Saffron Nage",
    category: "Seafood",
    subcategory: "Fish",
    chef: "Sofia Andreou",
    season: "Summer",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "The nage is built over three days. The sea bass is added at the very last moment.",
    technique: ["Nage", "Poaching", "Reduction"],
    ingredients: ["Sea Bass", "Fennel", "Saffron", "White Wine", "Pastis"],
    tags: ["fish", "seafood", "summer", "nage"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🐟",
    imageUrl:
      "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80",
    imageAlt: "Sea Bass, Fennel & Saffron Nage",
  },
  {
    id: 27,
    slug: "duck-breast-cherry-bitter-jus",
    title: "Duck Breast, Sour Cherry & Bitter Jus",
    category: "Grill & Fire",
    subcategory: "Duck",
    chef: "Tarık Yıldız",
    season: "Summer",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "Scored, seared skin-down for twelve minutes. The fat is sacred.",
    technique: ["Pan Searing", "Jus", "Reduction"],
    ingredients: [
      "Duck Breast",
      "Sour Cherry",
      "Red Wine",
      "Thyme",
      "Black Pepper",
    ],
    tags: ["duck", "grill", "summer", "cherry"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🍒",
    imageUrl:
      "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=800&q=80",
    imageAlt: "Duck Breast, Sour Cherry & Bitter Jus",
  },
  {
    id: 28,
    slug: "yuzu-tart-sesame-praline",
    title: "Yuzu Tart, Sesame Praline",
    category: "Pastry",
    subcategory: "Tarts",
    chef: "Kenji Tanaka",
    season: "Spring",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "Kenji's Japanese heritage on a French tart base. The yuzu curd takes two days.",
    technique: ["Curd Making", "Praline", "Blind Baking"],
    ingredients: [
      "Yuzu Juice",
      "Sesame Praline",
      "Butter Pastry",
      "Eggs",
      "Sugar",
    ],
    tags: ["dessert", "yuzu", "japanese", "tart"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🍋",
    imageUrl:
      "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&q=80",
    imageAlt: "Yuzu Tart, Sesame Praline",
  },
  {
    id: 29,
    slug: "foie-gras-brioche-quince",
    title: "Foie Gras, Toasted Brioche & Quince",
    category: "Signature Dishes",
    subcategory: "Foie Gras",
    chef: "Marco Bellini",
    season: "Autumn",
    year: 2023,
    badge: "Awarded",
    badgeStyle: "gold",
    description:
      "The brioche is baked each morning. The quince is from our supplier in Cappadocia.",
    technique: ["Searing", "Brioche Baking", "Quince Paste"],
    ingredients: ["Foie Gras", "Brioche", "Quince", "Armagnac", "Fleur de Sel"],
    tags: ["foie gras", "autumn", "awarded", "signature"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "wide",
    placeholder: "🫓",
    imageUrl:
      "https://images.unsplash.com/photo-1559847844-5315695dadae?w=800&q=80",
    imageAlt: "Foie Gras, Toasted Brioche & Quince",
  },
  {
    id: 30,
    slug: "porcini-tagliolini-black-garlic",
    title: "Porcini Tagliolini, Black Garlic & Sage",
    category: "Signature Dishes",
    subcategory: "Pasta",
    chef: "Marco Bellini",
    season: "Autumn",
    year: 2023,
    badge: null,
    badgeStyle: null,
    description:
      "Fresh pasta rolled each morning. The porcini are dried and rehydrated — never fresh from a jar.",
    technique: ["Fresh Pasta", "Reduction", "Fermentation"],
    ingredients: [
      "Porcini Mushrooms",
      "00 Flour",
      "Egg Yolk",
      "Black Garlic",
      "Sage",
      "Parmesan",
    ],
    tags: ["pasta", "mushroom", "autumn", "handmade"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "half",
    placeholder: "🍝",
    imageUrl:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
    imageAlt: "Porcini Tagliolini, Black Garlic & Sage",
  },
  {
    id: 31,
    slug: "razor-clams-almond-gazpacho",
    title: "Razor Clams, Almond Gazpacho",
    category: "Seafood",
    subcategory: "Clams",
    chef: "Sofia Andreou",
    season: "Summer",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "Inspired by a meal Sofia had in Cádiz in 2017. She's been chasing it ever since.",
    technique: ["Cold Cooking", "Emulsification", "Steaming"],
    ingredients: [
      "Razor Clams",
      "Marcona Almonds",
      "Cucumber",
      "White Grapes",
      "Sherry Vinegar",
    ],
    tags: ["seafood", "clams", "summer", "cold"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🦪",
    imageUrl:
      "https://images.unsplash.com/photo-1498654200943-1088dd4438ae?w=800&q=80",
    imageAlt: "Razor Clams, Almond Gazpacho",
  },
  {
    id: 32,
    slug: "roasted-cauliflower-tahini",
    title: "Roasted Cauliflower, Tahini & Pomegranate",
    category: "Seasonal",
    subcategory: "Vegetables",
    chef: "Leila Şahin",
    season: "Winter",
    year: 2024,
    badge: "Seasonal",
    badgeStyle: "sage",
    description:
      "The whole head roasted at 220°C. Split at the table. The pomegranate comes from Leila's hometown.",
    technique: ["High Heat Roasting", "Tahini Sauce"],
    ingredients: ["Cauliflower", "Tahini", "Pomegranate", "Cumin", "Lemon"],
    tags: ["vegetable", "winter", "seasonal", "middle-eastern"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🥦",
    imageUrl:
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
    imageAlt: "Roasted Cauliflower, Tahini & Pomegranate",
  },
  {
    id: 33,
    slug: "beef-tartare-truffle-egg",
    title: "Beef Tartare, Truffle & Aged Egg Yolk",
    category: "Signature Dishes",
    subcategory: "Tartare",
    chef: "Marco Bellini",
    season: "All Year",
    year: 2024,
    badge: "Signature",
    badgeStyle: "terra",
    description:
      "Served with warm toasts. The egg yolk has been cured in soy and mirin for 48 hours.",
    technique: ["Hand Cutting", "Curing", "Shaving"],
    ingredients: [
      "Beef Fillet",
      "Black Truffle",
      "Cured Egg Yolk",
      "Capers",
      "Cornichons",
    ],
    tags: ["tartare", "beef", "truffle", "signature"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "half",
    placeholder: "🥩",
    imageUrl:
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
    imageAlt: "Beef Tartare, Truffle & Aged Egg Yolk",
  },
  {
    id: 34,
    slug: "grilled-corn-smoked-butter",
    title: "Grilled Corn, Smoked Butter & Espelette",
    category: "Seasonal",
    subcategory: "Vegetables",
    chef: "Tarık Yıldız",
    season: "Summer",
    year: 2024,
    badge: "Summer",
    badgeStyle: "sage",
    description:
      "Corn on the cob over direct flame. The silk is removed after charring.",
    technique: ["Live Fire", "Smoking", "Charring"],
    ingredients: [
      "Corn",
      "Smoked Butter",
      "Espelette Pepper",
      "Sea Salt",
      "Lime",
    ],
    tags: ["vegetable", "summer", "fire", "corn"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🌽",
    imageUrl:
      "https://images.unsplash.com/photo-1601001815717-db56edab7a58?w=800&q=80",
    imageAlt: "Grilled Corn, Smoked Butter & Espelette",
  },
  {
    id: 35,
    slug: "wine-pairing-service",
    title: "The Pairing — Emre at the Table",
    category: "Events & Private Dining",
    subcategory: "Wine Service",
    chef: "Emre Kaya",
    season: "All Year",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "Every pairing explained. Every choice intentional. Emre never pours without a reason.",
    technique: ["Wine Service", "Pairing"],
    ingredients: [],
    tags: ["wine", "events", "service", "private dining"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "half",
    placeholder: "🍷",
    imageUrl:
      "https://images.unsplash.com/photo-1474722883778-792e7fb1f55d?w=800&q=80",
    imageAlt: "The Pairing — Emre at the Table",
  },
  {
    id: 36,
    slug: "panna-cotta-blood-orange",
    title: "Vanilla Panna Cotta, Blood Orange & Campari",
    category: "Pastry",
    subcategory: "Creams",
    chef: "Kenji Tanaka",
    season: "Winter",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "Set just enough to hold its shape when unmoulded. It should tremble when touched.",
    technique: ["Setting", "Reduction", "Maceration"],
    ingredients: ["Vanilla", "Cream", "Blood Orange", "Campari", "Sugar"],
    tags: ["dessert", "winter", "panna cotta", "citrus"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🍮",
    imageUrl:
      "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
    imageAlt: "Vanilla Panna Cotta, Blood Orange & Campari",
  },
  {
    id: 37,
    slug: "wagyu-a5-ponzu-ginger",
    title: "Wagyu A5, Ponzu & Fresh Ginger",
    category: "Signature Dishes",
    subcategory: "Beef",
    chef: "Tarık Yıldız",
    season: "All Year",
    year: 2024,
    badge: "Signature",
    badgeStyle: "terra",
    description:
      "Three slices. Twenty seconds on each side. Nothing more is needed.",
    technique: ["High Heat Searing", "Ponzu"],
    ingredients: [
      "Wagyu A5",
      "Ponzu",
      "Fresh Ginger",
      "Sesame",
      "Spring Onion",
    ],
    tags: ["wagyu", "beef", "japanese", "signature"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "half",
    placeholder: "🥩",
    imageUrl:
      "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&q=80",
    imageAlt: "Wagyu A5, Ponzu & Fresh Ginger",
  },
  {
    id: 38,
    slug: "stracciatella-roasted-peppers",
    title: "Stracciatella, Roasted Peppers & Anchovy",
    category: "Garde Manger",
    subcategory: "Cheese",
    chef: "Nora Hartmann",
    season: "Summer",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "The peppers are roasted directly over flame and peeled by hand. Cold, rich, precise.",
    technique: ["Fire Roasting", "Peeling"],
    ingredients: ["Stracciatella", "Red Peppers", "Anchovy", "Capers", "Basil"],
    tags: ["cheese", "summer", "garde manger", "cold"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "third",
    placeholder: "🧀",
    imageUrl:
      "https://images.unsplash.com/photo-1549017855-f9b2e613ab9a?w=800&q=80",
    imageAlt: "Stracciatella, Roasted Peppers & Anchovy",
  },
  {
    id: 39,
    slug: "lobster-bisque-cognac",
    title: "Lobster Bisque, Cognac & Tarragon Cream",
    category: "Seafood",
    subcategory: "Bisque",
    chef: "Sofia Andreou",
    season: "Winter",
    year: 2023,
    badge: "Awarded",
    badgeStyle: "gold",
    description:
      "Built from shells roasted until almost burnt. The cognac is added off the heat.",
    technique: ["Bisque", "Roasting", "Reduction"],
    ingredients: ["Lobster", "Cognac", "Tarragon", "Cream", "Tomato Paste"],
    tags: ["soup", "lobster", "winter", "awarded"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "wide",
    placeholder: "🦞",
    imageUrl:
      "https://images.unsplash.com/photo-1555126634-323283e090fa?w=800&q=80",
    imageAlt: "Lobster Bisque, Cognac & Tarragon Cream",
  },
  {
    id: 40,
    slug: "kitchen-brigade-morning",
    title: "Kitchen Brigade — Morning Briefing",
    category: "Behind the Scenes",
    subcategory: "Kitchen Life",
    chef: "Marco Bellini",
    season: "All Year",
    year: 2024,
    badge: null,
    badgeStyle: null,
    description:
      "Every day starts at 7 AM. Every dish is discussed before a single knife is picked up.",
    technique: [],
    ingredients: [],
    tags: ["behind the scenes", "kitchen", "team", "morning"],
    isFeatured: false,
    isRecentlyAdded: false,
    gridSize: "wide",
    placeholder: "👨‍🍳",
    imageUrl:
      "https://images.unsplash.com/photo-1581299894007-aaa50297cf16?w=800&q=80",
    imageAlt: "Kitchen Brigade — Morning Briefing",
  },
];

export default terraGalleryData;
