const categories = [
  {
    id: 1,
    name: "starters",
    icon: "🥗",
    type: "Light beginnings",
    items: [
      {
        id: 1,
        name: "cold starter",
        title: "Foie Gras Terrine",
        description: "Mango jam, brioche toast, micro herbs",
        price: "$28",
        type: "signature",
        chef_recommendation: true,
      },
      {
        id: 2,
        name: "warm starter",
        title: "Burrata & Heirloom Tomato",
        description: "Aged balsamic, fresh basil oil, sea salt flakes",
        price: "$24",
        type: "vegetarian",
        chef_recommendation: false,
      },
      {
        id: 3,
        name: "cold starter",
        title: "Tuna Tartare",
        description: "Avocado, sesame oil, soy glaze, crispy wontons",
        price: "$26",
        type: "spicy",
        chef_recommendation: false,
      },
      {
        id: 4,
        name: "warm starter",
        title: "Truffle Arancini",
        description: "Black truffle, aged parmesan, saffron aioli",
        price: "$18",
        type: ["vegetarian", "seasonal"],
        chef_recommendation: false,
      },
      {
        id: 5,
        name: "cold starter",
        title: "Scallop Ceviche",
        description: "Citrus dressing, cucumber, radish, chili oil",
        price: "$24",
        type: "spicy",
        chef_recommendation: false,
      },
      {
        id: 6,
        name: "warm starter",
        title: "Wild Mushroom Crostini",
        description: "Sourdough, garlic butter, fresh thyme, ricotta",
        price: "$16",
        type: "vegetarian",
        chef_recommendation: false,
      },
    ],
  },

  {
    id: 2,
    name: "soups",
    icon: "🍲",
    type: "Warm & comforting",
    items: [
      {
        id: 1,
        title: "Lobster Bisque",
        description: "Creamy lobster broth, chives, cognac cream",
        price: "$18",
        type: "signature",
        chef_recommendation: true,
      },
      {
        id: 2,
        title: "French Onion Soup",
        description: "Caramelized onions, beef broth, gruyère toast",
        price: "$16",
        type: "classic",
        chef_recommendation: false,
      },
      {
        id: 3,
        title: "Wild Mushroom Velouté",
        description: "Forest mushrooms, thyme oil, parmesan crisp",
        price: "$17",
        type: "vegetarian",
        chef_recommendation: false,
      },
      {
        id: 4,
        title: "Tomato Basil Soup",
        description: "Roasted tomatoes, basil cream, sourdough crumbs",
        price: "$14",
        type: "vegetarian",
        chef_recommendation: false,
      },
      {
        id: 5,
        title: "Thai Coconut Shrimp Soup",
        description: "Coconut milk, shrimp, lime, chili, coriander",
        price: "$19",
        type: "spicy",
        chef_recommendation: true,
      },
    ],
  },

  {
    id: 3,
    name: "main course",
    icon: "🍽️",
    type: "The heart of the meal",
    items: [
      {
        id: 1,
        title: "Filet Mignon",
        description: "Potato purée, asparagus, red wine reduction",
        price: "$48",
        type: "signature",
        chef_recommendation: true,
      },
      {
        id: 2,
        title: "Duck Breast",
        description: "Cherry glaze, parsnip purée, baby carrots",
        price: "$42",
        type: "seasonal",
        chef_recommendation: false,
      },
      {
        id: 3,
        title: "Truffle Risotto",
        description: "Arborio rice, black truffle, aged parmesan",
        price: "$34",
        type: "vegetarian",
        chef_recommendation: true,
      },
      {
        id: 4,
        title: "Lamb Rack",
        description: "Rosemary crust, garlic potatoes, demi-glace",
        price: "$46",
        type: "signature",
        chef_recommendation: false,
      },
      {
        id: 5,
        title: "Chicken Supreme",
        description: "Herb butter sauce, seasonal vegetables",
        price: "$32",
        type: "classic",
        chef_recommendation: false,
      },
      {
        id: 6,
        title: "Braised Short Rib",
        description: "Creamy polenta, roasted shallots, thyme jus",
        price: "$40",
        type: "slow cooked",
        chef_recommendation: true,
      },
      {
        id: 7,
        title: "Pesto Linguine",
        description: "Fresh basil pesto, pine nuts, pecorino cheese",
        price: "$28",
        type: "vegetarian",
        chef_recommendation: false,
      },
      {
        id: 8,
        title: "Veal Milanese",
        description: "Arugula salad, lemon dressing, parmesan flakes",
        price: "$39",
        type: "classic",
        chef_recommendation: false,
      },
    ],
  },

  {
    id: 4,
    name: "seafood",
    icon: "🦞",
    type: "Fresh from the sea",
    items: [
      {
        id: 1,
        title: "Grilled Atlantic Salmon",
        description: "Lemon beurre blanc, asparagus, herb potatoes",
        price: "$38",
        type: "signature",
        chef_recommendation: true,
      },
      {
        id: 2,
        title: "Butter Garlic Lobster",
        description: "Drawn butter, herbs, roasted vegetables",
        price: "$56",
        type: "premium",
        chef_recommendation: true,
      },
      {
        id: 3,
        title: "Seared Sea Bass",
        description: "Fennel purée, citrus salad, saffron sauce",
        price: "$44",
        type: "seasonal",
        chef_recommendation: false,
      },
      {
        id: 4,
        title: "Shrimp Scampi",
        description: "White wine garlic sauce, linguine pasta",
        price: "$32",
        type: "classic",
        chef_recommendation: false,
      },
      {
        id: 5,
        title: "Blackened Tuna Steak",
        description: "Sesame crust, soy glaze, pickled cucumber",
        price: "$36",
        type: "spicy",
        chef_recommendation: false,
      },
      {
        id: 6,
        title: "Seafood Paella",
        description: "Mussels, shrimp, calamari, saffron rice",
        price: "$48",
        type: "signature",
        chef_recommendation: true,
      },
    ],
  },

  {
    id: 5,
    name: "drinks",
    icon: "🍸",
    type: "Wines & Cocktails",
    items: [
      {
        id: 1,
        title: "Classic Mojito",
        description: "White rum, mint, lime, soda water",
        price: "$14",
        type: "cocktail",
      },
      {
        id: 2,
        title: "Espresso Martini",
        description: "Vodka, espresso, coffee liqueur",
        price: "$16",
        type: "cocktail",
      },
      {
        id: 3,
        title: "Negroni",
        description: "Gin, Campari, sweet vermouth",
        price: "$15",
        type: "classic",
      },
      {
        id: 4,
        title: "French 75",
        description: "Gin, champagne, lemon juice",
        price: "$18",
        type: "sparkling",
      },
      {
        id: 5,
        title: "Passionfruit Spritz",
        description: "Passionfruit purée, prosecco, soda",
        price: "$15",
        type: "refreshing",
      },
      {
        id: 6,
        title: "Smoked Old Fashioned",
        description: "Bourbon, bitters, smoked orange peel",
        price: "$19",
        type: "signature",
      },
      {
        id: 7,
        title: "Fresh Lemonade",
        description: "Lemon juice, mint, sparkling water",
        price: "$9",
        type: "non-alcoholic",
      },
      {
        id: 8,
        title: "Berry Smoothie",
        description: "Mixed berries, yogurt, honey",
        price: "$10",
        type: "healthy",
      },
      {
        id: 9,
        title: "Iced Matcha Latte",
        description: "Ceremonial matcha, oat milk, vanilla",
        price: "$11",
        type: "tea",
      },
      {
        id: 10,
        title: "House Red Wine",
        description: "Dry red wine selection from Tuscany",
        price: "$13",
        type: "wine",
      },
      {
        id: 11,
        title: "Craft IPA Beer",
        description: "Locally brewed India pale ale",
        price: "$12",
        type: "beer",
      },
      {
        id: 12,
        title: "Sparkling Water",
        description: "Premium mineral sparkling water",
        price: "$6",
        type: "soft drink",
      },
    ],
  },

  {
    id: 6,
    name: "desserts",
    icon: "🍰",
    type: "Sweet endings",
    items: [
      {
        id: 1,
        title: "Chocolate Lava Cake",
        description: "Warm chocolate center, vanilla bean ice cream",
        price: "$16",
        type: "signature",
        chef_recommendation: true,
      },
      {
        id: 2,
        title: "Crème Brûlée",
        description: "Vanilla custard, caramelized sugar crust",
        price: "$14",
        type: "classic",
        chef_recommendation: false,
      },
      {
        id: 3,
        title: "Tiramisu",
        description: "Espresso-soaked ladyfingers, mascarpone cream",
        price: "$15",
        type: "italian",
        chef_recommendation: false,
      },
      {
        id: 4,
        title: "Berry Pavlova",
        description: "Meringue shell, fresh berries, whipped cream",
        price: "$13",
        type: "seasonal",
        chef_recommendation: false,
      },
      {
        id: 5,
        title: "Pistachio Cheesecake",
        description: "Creamy pistachio filling, biscuit crust",
        price: "$15",
        type: "signature",
        chef_recommendation: true,
      },
      {
        id: 6,
        title: "Affogato",
        description: "Vanilla gelato topped with hot espresso",
        price: "$12",
        type: "coffee dessert",
        chef_recommendation: false,
      },
    ],
  },
];

export default categories;
